
CC = gcc
# asked options
CFLAGS = -Wall -Wextra -std=c99 -O2
# grant access to the math.h lib
LDLIBS = -lm 

main: NeuralNetwork.o Utility.o main.o

clean:
	${RM} main
	${RM} NeuralNetwork.o Utility.o main.o 
# END
